version: '3'
services:
  app:
    image: node:16.13.1
    ports:
      - 3000:3000
    working_dir: /var/www
    user: node
    tty: true
    volumes:
      - ./:/var/www
    links:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}